#![deny(missing_docs)]
#![forbid(unsafe_code)]
#![allow(clippy::pedantic)]

//! # pcloud-web
//!
//! MVP Web UI scaffold for the pcloud-rs daemon (PLAN_A_PLUS §P4.5).
//!
//! This crate is intentionally **minimal**: it exposes a small Axum HTTP
//! server that binds to `127.0.0.1` by default and renders a plain-HTML status page and
//! a tiny JSON status endpoint by calling the daemon over the existing
//! UNIX-socket IPC transport in [`pcloud_ipc`].
//!
//! It is **not** the final Leptos SSR application described in the plan.
//! It is the scaffold that later work will build on. The default bind address,
//! Host/Origin checks, web-token gate, and minimal Content-Security-Policy are
//! wired here from day one so follow-up UI work inherits safe defaults instead
//! of tightening them afterwards.
//!
//! ## Security posture
//!
//! - **Loopback default.** The server binds to `127.0.0.1` by default. Tests
//!   and lab deployments may bind to all interfaces with an explicit
//!   `--bind 0.0.0.0:17650` / `WebConfig::bind_addr`, but non-local browser
//!   `Host` values must be added with `--allow-host`.
//! - **No CORS, no cross-origin access.** Same-origin policy only. No
//!   `Access-Control-*` headers are emitted.
//! - **Host and origin enforcement.** Requests must use loopback/local
//!   `Host` values (or an explicitly configured reverse-proxy host), and
//!   mutating requests must carry a same-origin `Origin` or `Referer`.
//! - **Strict Content-Security-Policy.** Every HTML response carries
//!   the minimal policy
//!   `default-src 'self'; script-src 'none'; style-src 'self' 'unsafe-inline'`.
//!   This disables all JavaScript and restricts subresources to the
//!   same origin. `'unsafe-inline'` on styles is a temporary
//!   concession for the scaffold's inline `<style>` block and is
//!   expected to be replaced with hashed styles or an external
//!   stylesheet when the real Leptos SSR UI lands.
//! - **`X-Content-Type-Options: nosniff`** on HTML responses to prevent
//!   browser MIME-type sniffing.
//! - **Same-user execution model.** The web process is expected to run
//!   as the same local user as the daemon; IPC permission checks
//!   (owner-only UNIX socket) are enforced by [`pcloud_ipc`].
//! - **Per-request web token.** Every daemon-backed route requires
//!   `X-PCloud-Web-Token`. Only minimal liveness/readiness probes are
//!   intentionally unauthenticated. This is a separate defence from the
//!   owner-only IPC socket because loopback TCP does not prove same-UID
//!   access.
//! - **No credential handling.** This crate never reads or renders daemon
//!   auth tokens, passwords, or crypto passphrases. The web session token
//!   is generated by the caller, stored in memory as a redacted/zeroizing
//!   secret inside request state, and written to an owner-only runtime file
//!   for local operators.
//!
//! ## IPC client pattern
//!
//! The routes call into the daemon with the synchronous
//! [`pcloud_ipc::IpcClient::send`] helper, which performs a blocking
//! UNIX-socket round trip. To avoid blocking the Tokio runtime, every
//! IPC call is dispatched on a blocking worker pool via
//! [`tokio::task::spawn_blocking`]. The rendered status summary is
//! intentionally best-effort: unreachable daemon, transport error, or
//! join failure all degrade gracefully to an "Offline" page rather
//! than propagating a 5xx.
//!
//! ## Honest limitations
//!
//! - **Status parsing is best-effort.** The landing page and
//!   `/api/status` endpoint parse the daemon's IPC response on a
//!   field-by-field allow-list; fields the daemon does not return
//!   (because an older daemon predates them, or because the IPC shape
//!   changed) are rendered as `"unknown"` rather than failing the
//!   request. Callers needing strict schema validation must use a
//!   direct IPC client instead of the web UI.
//! - **Scaffold, not the final UI.** This crate is the MVP described in
//!   PLAN_A_PLUS §P4.5, not the Leptos SSR application that will
//!   eventually replace it. The inline templating in
//!   `pcloud_web::templates` is expected to be removed wholesale when
//!   the real UI lands.
//! - **No metrics endpoint.** `GET /metrics` returns 404 by design
//!   here; the metrics surface is compiled into the daemon, not the
//!   web scaffold.
//!
//! # Example
//!
//! ```no_run
//! use pcloud_web::{WebConfig, serve};
//! use std::path::PathBuf;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), pcloud_web::WebError> {
//!     let config = WebConfig {
//!         socket_path: PathBuf::from("/run/user/1000/pcloud-rs.sock"),
//!         bind_addr: "127.0.0.1:17650".parse().unwrap(),
//!         ..WebConfig::default()
//!     };
//!     serve(config).await
//! }
//! ```

// **PLATFORM:** all
// **GATING:** none (portable).

use std::fmt;
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

use pcloud_secret::{ExposeSecret, secret_string::SecretString};
use thiserror::Error;

mod routes;
mod templates;

use routes::router;

/// Default bind address for the MVP web UI.
///
/// Intentionally loopback by default. Use an explicit `--bind` /
/// [`WebConfig::bind_addr`] for lab or integration testing on other interfaces.
pub const DEFAULT_BIND_ADDR: SocketAddr =
    SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 17650);

/// Generate a cryptographically random 64-hex-char session token.
///
/// Returns an error string if the kernel CSPRNG is unavailable.
/// Callers that cannot tolerate failure should use [`generate_web_token_or_panic`].
///
/// # Errors
///
/// Returns `Err` with a descriptive string if `getrandom` fails.
pub fn generate_web_token() -> Result<String, String> {
    let mut buf = [0u8; 32];
    getrandom::getrandom(&mut buf)
        .map_err(|e| format!("getrandom: kernel RNG unavailable: {e}"))?;
    let mut s = String::with_capacity(64);
    for b in buf {
        use std::fmt::Write as _;
        let _ = write!(&mut s, "{b:02x}");
    }
    Ok(s)
}

/// Generate a session token, panicking if the kernel RNG is unavailable.
///
/// This is a convenience wrapper around [`generate_web_token`] for call
/// sites inside [`Default`] implementations where returning an error is
/// not possible. If you can propagate errors, prefer [`generate_web_token`].
#[must_use]
pub fn generate_web_token_or_panic() -> String {
    // SAFETY: This helper is documented as a panic-on-RNG-failure wrapper
    // for `Default`-style call sites that cannot propagate errors. A host
    // whose kernel CSPRNG is unavailable cannot start a web UI securely,
    // so panic is the correct failure mode here. Callers able to surface
    // errors should use `generate_web_token` directly.
    generate_web_token().expect("getrandom: kernel RNG unavailable — cannot start web UI")
}

/// Runtime configuration for [`serve`].
///
/// Construct explicitly or via [`WebConfig::default`] (loopback default bind,
/// empty socket path — daemon reports as "offline" until a real socket
/// path is supplied).
///
/// # Fields
///
/// - [`WebConfig::socket_path`] — absolute path to the daemon's
///   owner-only UNIX socket. An empty path is treated as "no daemon
///   configured" and the UI renders a permanent Offline page without
///   ever touching the filesystem. This is the expected state in unit
///   tests and in the test fixtures.
/// - [`WebConfig::bind_addr`] — the socket address the HTTP server
///   binds to. The default port is `17650` ([`DEFAULT_BIND_ADDR`]).
///   Binding to all interfaces is allowed for testing, but remote
///   browser `Host` values still need explicit [`WebConfig::allowed_hosts`].
/// - [`WebConfig::web_token`] — session token required by every
///   daemon-backed route via the `X-PCloud-Web-Token` header. Generate at
///   daemon startup with [`generate_web_token`] and direct operators to the
///   owner-only runtime token file.
/// - [`WebConfig::allowed_hosts`] — optional additional `Host` allow-list
///   entries for same-host reverse proxies. Loopback/local hosts are always
///   allowed; non-loopback entries must be configured explicitly.
/// - [`WebConfig::ready`] — shared readiness flag. Set to `true` after
///   daemon initialization completes. The `/readyz` route returns 503
///   until this flag is set, enabling orchestrators to gate traffic
///   on full daemon readiness rather than mere process liveness.
pub struct WebConfig {
    /// Filesystem path to the daemon's UNIX IPC socket.
    ///
    /// When empty, the web UI short-circuits every status fetch to
    /// "offline" without attempting a UNIX-socket connection.
    pub socket_path: PathBuf,
    /// Address to bind the HTTP server to. Defaults to loopback; tests may
    /// override this to `0.0.0.0` / `::` when exercising remote access.
    pub bind_addr: SocketAddr,
    /// Session token for web management routes.
    ///
    /// Callers supply `X-PCloud-Web-Token: <token>` on every daemon-backed
    /// request. Liveness/readiness probes do not require it. Generate with
    /// [`generate_web_token`]. Wrapped in [`SecretString`] so accidental
    /// `Debug` / log emission is redacted and the buffer is zeroized on
    /// drop. CLAUDEREV iter-1 SEC-H finding fix.
    pub web_token: SecretString,
    /// Additional accepted `Host` values for same-host reverse proxies.
    ///
    /// Values are matched case-insensitively as host names or `host:port`
    /// authorities. Loopback hosts (`localhost`, `127.0.0.0/8`, `::1`) are
    /// always accepted, so this list is only for explicitly configured
    /// reverse-proxy names or LAN testing addresses such as
    /// `pcloud-admin.internal` or `192.0.2.10:17650`.
    pub allowed_hosts: Vec<String>,
    /// Readiness flag. `/readyz` returns 503 until this is `true`.
    ///
    /// Flip to `true` after daemon initialization completes so
    /// orchestrators (k8s, systemd socket-activated unit checks, etc.)
    /// can gate live traffic on full daemon readiness, not just process
    /// liveness. Defaults to `false` (not ready) at construction.
    pub ready: Arc<AtomicBool>,
}

impl fmt::Debug for WebConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("WebConfig")
            .field("socket_path", &self.socket_path)
            .field("bind_addr", &self.bind_addr)
            .field("web_token", &"<redacted>")
            .field("allowed_hosts", &self.allowed_hosts)
            .field("ready", &self.ready)
            .finish()
    }
}

impl Default for WebConfig {
    fn default() -> Self {
        Self {
            socket_path: PathBuf::new(),
            bind_addr: DEFAULT_BIND_ADDR,
            web_token: SecretString::new(generate_web_token_or_panic()),
            allowed_hosts: Vec::new(),
            ready: Arc::new(AtomicBool::new(false)),
        }
    }
}

/// Errors returned by [`serve`].
///
/// The variants distinguish *pre-serve* failures (bind) from *serve-time*
/// failures (hyper/Axum) so callers can decide whether the problem is a
/// configuration issue (port in use, permission denied) or a runtime
/// failure after the listener was already accepting connections.
///
#[derive(Debug, Error)]
pub enum WebError {
    /// The underlying TCP bind failed.
    ///
    /// Typical causes: port already in use, insufficient privileges,
    /// or address not assigned to any interface.
    #[error("bind {addr}: {source}")]
    Bind {
        /// Address we attempted to bind.
        addr: SocketAddr,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// Error returned by the Axum / hyper server after bind.
    ///
    /// Covers post-bind `accept()` / I/O failures surfaced by
    /// [`axum::serve()`].
    #[error("serve: {0}")]
    Serve(#[source] std::io::Error),
}

/// Shared application state passed to every request handler.
///
/// Wraps the daemon socket path in an [`Arc`] so cloning the state per
/// request is cheap and does not copy the `PathBuf`. This struct is
/// intentionally tiny — routes do **not** hold long-lived IPC clients,
/// authentication tokens, or any secret material. Each request that
/// needs daemon data opens a fresh UNIX-socket connection via
/// [`pcloud_ipc::IpcClient::send`].
#[derive(Debug, Clone)]
pub(crate) struct AppState {
    /// Path to the daemon's UNIX IPC socket. Shared via [`Arc`] so
    /// cloning the state is cheap. An empty path is treated as "no
    /// daemon configured" by the request handlers.
    pub socket_path: Arc<PathBuf>,
    /// Session token required by daemon-backed routes. Stored in an [`Arc`]
    /// around a [`SecretString`] so the token is zeroized when the last
    /// [`AppState`] clone is dropped, and never appears in `Debug` output.
    pub web_token: Arc<SecretString>,
    /// Bound address used to validate local `Host` ports.
    pub bind_addr: SocketAddr,
    /// Additional reverse-proxy host names accepted by the Host allow-list.
    pub allowed_hosts: Arc<Vec<String>>,
    /// Readiness flag shared with the daemon. `/readyz` returns 503
    /// until this flips to `true`.
    pub ready: Arc<AtomicBool>,
}

/// Write the web session token to `$XDG_RUNTIME_DIR/pcloud-daemon/web-token`
/// with mode 0600.
///
/// Returns the path the token was written to on success, or an I/O error
/// description on failure. The token value itself is never logged or returned
/// in the error — callers must not include it in any log output.
///
/// Security rationale: stderr output (eprintln!) is captured verbatim by
/// systemd-journal, Docker log drivers, and CI log collectors. Any process
/// with journal-read privileges would see the token in cleartext. Writing to
/// a 0600 file under the per-user runtime directory limits readability to the
/// daemon owner and is consistent with the token-vault discipline used by the
/// rest of the daemon (ADR 0005, ADR 0015).
fn write_web_token_to_runtime_dir(token: &str) -> Result<PathBuf, std::io::Error> {
    // Prefer XDG_RUNTIME_DIR (set by PAM/systemd for every login session).
    // When absent, return an error so the caller can fall back gracefully;
    // guessing the uid without unsafe code is not worth the complexity.
    let runtime_dir = std::env::var_os("XDG_RUNTIME_DIR")
        .map(PathBuf::from)
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "XDG_RUNTIME_DIR is not set; cannot locate runtime directory for token file",
            )
        })?;
    write_web_token_to_dir(&runtime_dir, token)
}

fn write_web_token_to_dir(runtime_dir: &Path, token: &str) -> Result<PathBuf, std::io::Error> {
    use std::fs;
    use std::io::Write as _;

    let token_dir = runtime_dir.join("pcloud-daemon");
    #[cfg(unix)]
    validate_owner_only_dir(runtime_dir)?;
    #[cfg(unix)]
    let token_dir_preexisted = fs::symlink_metadata(&token_dir).is_ok();
    fs::create_dir_all(&token_dir)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if !token_dir_preexisted {
            fs::set_permissions(&token_dir, fs::Permissions::from_mode(0o700))?;
        }
        validate_owner_only_dir(&token_dir)?;
    }

    let token_path = token_dir.join("web-token");
    let (tmp_path, mut file) = create_new_token_temp(&token_dir)?;
    file.write_all(token.as_bytes())?;
    file.sync_all()?;
    drop(file);
    fs::rename(&tmp_path, &token_path)?;
    #[cfg(unix)]
    {
        sync_dir(&token_dir)?;
        validate_owner_only_file(&token_path)?;
    }
    Ok(token_path)
}

fn create_new_token_temp(token_dir: &Path) -> Result<(PathBuf, std::fs::File), std::io::Error> {
    #[cfg(unix)]
    use std::os::unix::fs::OpenOptionsExt as _;

    for _ in 0..8 {
        let tmp_path = token_dir.join(format!("web-token.tmp.{}", random_hex_suffix()?));
        let mut opts = std::fs::OpenOptions::new();
        opts.write(true).create_new(true);
        #[cfg(unix)]
        {
            opts.mode(0o600).custom_flags(libc::O_NOFOLLOW);
        }
        match opts.open(&tmp_path) {
            Ok(file) => return Ok((tmp_path, file)),
            Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(err) => return Err(err),
        }
    }
    Err(std::io::Error::new(
        std::io::ErrorKind::AlreadyExists,
        "could not allocate a unique web-token temp file",
    ))
}

fn random_hex_suffix() -> Result<String, std::io::Error> {
    let mut buf = [0u8; 16];
    getrandom::getrandom(&mut buf)
        .map_err(|err| std::io::Error::other(format!("getrandom failed: {err}")))?;
    let mut out = String::with_capacity(32);
    for b in buf {
        use std::fmt::Write as _;
        let _ = write!(&mut out, "{b:02x}");
    }
    Ok(out)
}

#[cfg(unix)]
fn validate_owner_only_dir(path: &Path) -> Result<(), std::io::Error> {
    use std::os::unix::fs::MetadataExt;

    let meta = std::fs::symlink_metadata(path)?;
    if meta.file_type().is_symlink() || !meta.file_type().is_dir() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!("{} must be a real directory", path.display()),
        ));
    }
    let expected_uid = pcloud_ipc::current_effective_uid();
    if meta.uid() != expected_uid {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!(
                "{} is owned by uid {}, expected uid {}",
                path.display(),
                meta.uid(),
                expected_uid
            ),
        ));
    }
    let mode = meta.mode() & 0o777;
    if mode & 0o077 != 0 {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!(
                "{} must not grant group/other access (mode=0o{mode:o})",
                path.display()
            ),
        ));
    }
    Ok(())
}

#[cfg(unix)]
fn validate_owner_only_file(path: &Path) -> Result<(), std::io::Error> {
    use std::os::unix::fs::MetadataExt;

    let meta = std::fs::symlink_metadata(path)?;
    if meta.file_type().is_symlink() || !meta.file_type().is_file() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!("{} must be a regular file", path.display()),
        ));
    }
    let expected_uid = pcloud_ipc::current_effective_uid();
    if meta.uid() != expected_uid {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!(
                "{} is owned by uid {}, expected uid {}",
                path.display(),
                meta.uid(),
                expected_uid
            ),
        ));
    }
    let mode = meta.mode() & 0o777;
    if mode != 0o600 {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            format!("{} must be mode 0600 (mode=0o{mode:o})", path.display()),
        ));
    }
    Ok(())
}

#[cfg(unix)]
fn sync_dir(path: &Path) -> Result<(), std::io::Error> {
    std::fs::File::open(path)?.sync_all()
}

/// Start the Web UI MVP on the configured bind address.
///
/// Creates internal shared state from the supplied configuration, builds the
/// three-route Axum router (`/`, `/api/status`, `/health`), binds a
/// TCP listener on `config.bind_addr`, and drives
/// [`axum::serve()`] until an unrecoverable I/O error occurs.
///
/// The function returns only on error; successful operation blocks
/// forever. Callers that need cooperative shutdown should run this on
/// its own task and drop/abort it when they want to stop serving.
///
/// # Errors
///
/// - [`WebError::Bind`] if binding the TCP listener fails (port in
///   use, permission denied, etc.).
/// - [`WebError::Serve`] if the Axum/hyper server returns an I/O
///   error after a successful bind.
///
pub async fn serve(config: WebConfig) -> Result<(), WebError> {
    // Write the web session token to a mode-0600 file under the runtime
    // directory rather than emitting it to stderr. stderr output is
    // captured verbatim by systemd-journal and other logging pipelines,
    // making it visible to any process that can read the journal — a wider
    // audience than the token's intended consumers. Writing to a 0600 file
    // restricts readability to the daemon owner, and `log::info!` directs
    // operators to the file path without exposing the token value itself.
    let token_written = write_web_token_to_runtime_dir(config.web_token.expose_secret());
    match token_written {
        Ok(ref token_path) => {
            log::info!(
                "pcloud-web: session token written to {}",
                token_path.display()
            );
        }
        Err(ref e) => {
            // Fall back to log::warn so operators know where to look;
            // never emit the token value to stderr or to the log.
            log::warn!(
                "pcloud-web: could not write session token to runtime dir ({}); \
                 retrieve it via `pcloudc web-token`",
                e
            );
        }
    }

    let state = AppState {
        socket_path: Arc::new(config.socket_path),
        web_token: Arc::new(config.web_token),
        bind_addr: config.bind_addr,
        allowed_hosts: Arc::new(config.allowed_hosts),
        ready: config.ready,
    };
    let app = router(state);

    let listener = tokio::net::TcpListener::bind(config.bind_addr)
        .await
        .map_err(|source| WebError::Bind {
            addr: config.bind_addr,
            source,
        })?;

    axum::serve(listener, app.into_make_service())
        .await
        .map_err(WebError::Serve)
}

/// Bind a listener without starting serving. Intended for integration
/// tests that need to pick an ephemeral port and learn it before making
/// requests.
///
/// Returns the bound listener, the resolved local [`SocketAddr`]
/// (useful when `bind_addr.port() == 0`), and the fully-constructed
/// [`axum::Router`] so the test can drive it with its own hyper
/// executor.
///
/// # Errors
///
/// Same as [`serve`] for the bind phase.
///
#[doc(hidden)]
pub async fn bind_for_test(
    config: WebConfig,
) -> Result<(tokio::net::TcpListener, SocketAddr, axum::Router), WebError> {
    let state = AppState {
        socket_path: Arc::new(config.socket_path),
        web_token: Arc::new(config.web_token),
        bind_addr: config.bind_addr,
        allowed_hosts: Arc::new(config.allowed_hosts),
        ready: config.ready,
    };
    let app = router(state);
    let listener = tokio::net::TcpListener::bind(config.bind_addr)
        .await
        .map_err(|source| WebError::Bind {
            addr: config.bind_addr,
            source,
        })?;
    let local = listener.local_addr().map_err(WebError::Serve)?;
    Ok((listener, local, app))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(unix)]
    use std::os::unix::fs::PermissionsExt;

    #[test]
    fn default_bind_is_loopback() {
        assert!(DEFAULT_BIND_ADDR.ip().is_loopback());
        assert_eq!(DEFAULT_BIND_ADDR.port(), 17650);
    }

    #[test]
    fn non_loopback_bind_is_allowed_for_testing() {
        // Use tokio's current-thread runtime so we can drive the async
        // bind without starting an endless server.
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();
        let cfg = WebConfig {
            socket_path: PathBuf::from("/tmp/nonexistent.sock"),
            bind_addr: "0.0.0.0:0".parse().unwrap(),
            ..WebConfig::default()
        };
        let (_listener, addr, _app) = rt.block_on(bind_for_test(cfg)).expect("bind wildcard");
        assert_ne!(addr.port(), 0);
    }

    #[test]
    fn web_config_debug_redacts_token() {
        let cfg = WebConfig {
            web_token: SecretString::new("unique-debug-token".to_owned()),
            ..WebConfig::default()
        };
        let rendered = format!("{cfg:?}");
        assert!(rendered.contains("<redacted>"));
        assert!(!rendered.contains("unique-debug-token"));
    }

    #[cfg(unix)]
    #[test]
    fn web_token_file_is_atomic_owner_only_file() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::set_permissions(tmp.path(), std::fs::Permissions::from_mode(0o700)).unwrap();

        let token_path = write_web_token_to_dir(tmp.path(), "test-web-token").expect("write token");

        assert_eq!(
            std::fs::read_to_string(&token_path).unwrap(),
            "test-web-token"
        );
        let meta = std::fs::symlink_metadata(&token_path).unwrap();
        assert!(meta.file_type().is_file());
        assert_eq!(meta.permissions().mode() & 0o777, 0o600);
    }

    #[cfg(unix)]
    #[test]
    fn web_token_writer_rejects_symlink_token_dir() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::set_permissions(tmp.path(), std::fs::Permissions::from_mode(0o700)).unwrap();
        let target = tmp.path().join("target");
        std::fs::create_dir(&target).unwrap();
        std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o700)).unwrap();
        std::os::unix::fs::symlink(&target, tmp.path().join("pcloud-daemon")).unwrap();

        let err =
            write_web_token_to_dir(tmp.path(), "test-web-token").expect_err("symlink dir rejected");
        assert_eq!(err.kind(), std::io::ErrorKind::PermissionDenied);
    }

    #[cfg(unix)]
    #[test]
    fn web_token_writer_rejects_group_readable_token_dir() {
        let tmp = tempfile::tempdir().unwrap();
        std::fs::set_permissions(tmp.path(), std::fs::Permissions::from_mode(0o700)).unwrap();
        let token_dir = tmp.path().join("pcloud-daemon");
        std::fs::create_dir(&token_dir).unwrap();
        std::fs::set_permissions(&token_dir, std::fs::Permissions::from_mode(0o755)).unwrap();

        let err =
            write_web_token_to_dir(tmp.path(), "test-web-token").expect_err("weak dir rejected");
        assert_eq!(err.kind(), std::io::ErrorKind::PermissionDenied);
    }
}
